[package]
name = "persist-core"
version = "0.1.0"
edition = "2018"
authors = ["Nicolas Polomack <nicolas@polomack.eu>"]
description = "Core library for persist, the process manager"
repository = "https://github.com/Hirevo/persist"
categories = ["command-line-utilities"]
keywords = ["process", "system", "monitor"]
license = "MIT OR Apache-2.0"

maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
chrono = { version = "0.4.10", features = ["serde"] }
thiserror = { version = "1.0.6" }
dirs = { version = "2.0.2" }

# error aggregate
tokio = { version = "=0.2.0-alpha.6", features = ["macros", "process"] }
heim = { version = "0.0.8" }
json = { package = "serde_json", version = "1.0.41" }
nix = { version = "0.15.0" }
