[package]
name = "persist-core"
version = "0.1.0"
edition = "2018"
authors = ["Nicolas Polomack <nicolas@polomack.eu>"]
description = "Core library for persist, the process manager"
repository = "https://github.com/Hirevo/persist"
categories = ["command-line-utilities"]
keywords = ["process", "system", "monitor"]
license = "MIT OR Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
chrono = { version = "0.4.10", features = ["serde"] }
thiserror = "1.0.9"
dirs = "2.0.2"

# error aggregate
tokio-util = { version = "0.2.0", features = ["codec"] }
json = { package = "serde_json", version = "1.0.44" }
heim = "0.0.9"
nix = "0.16.1"
